FROM ghcr.io/asen23/base@sha256:a67c2a161dc35c9f4e8d2027bb02bdeda3ec0e931e66cc4f790ff7239be6d6ea as work

COPY ./packages.work /work-packages

COPY ./repo/vscode.repo /etc/yum.repos.d/vscode.repo

RUN dnf -y upgrade && \
    dnf -y install $(<work-packages) && \
    dnf -y install java-17-openjdk java-17-openjdk-devel --releasever=41 && \
    dnf clean all

RUN rm /work-packages
