FROM ghcr.io/asen23/base@sha256:045f41fe600b6b11fc50e1689dc86c3d1dd11fa3999ac8b2bd08a2528ded0a9f as work

COPY ./packages.work /work-packages

COPY ./repo/vscode.repo /etc/yum.repos.d/vscode.repo

RUN dnf -y upgrade && \
    dnf -y install $(<work-packages) && \
    dnf -y install java-17-openjdk java-17-openjdk-devel --releasever=41 && \
    dnf clean all

RUN rm /work-packages
