name: build-work
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Containerfile.work'
      - 'packages.work'
  push:
    branches:
      - main
    paths:
      - 'Containerfile.work'
      - 'packages.work'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-image:
    name: Build Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      base_name: work
