name: build-base
on:
  pull_request:
    branches:
      - main
    paths:
      - 'Containerfile.base'
      - 'packages.base'
  push:
    branches:
      - main
    paths:
      - 'Containerfile.base'
      - 'packages.base'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-image:
    name: Build Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      base_name: base
